create extension if not exists pgcrypto;

create or replace function public.set_updated_at() returns trigger language plpgsql as $$ begin new.updated_at = now(); return new; end $$;

create table if not exists site_settings (
  id bigint primary key default 1 check (id = 1), club_name text not null default 'ANSTERDAM NIGHT CLUB', location_name text default 'PLANÈTE', address text default 'Dubréka, T10 Rond-point Planète',
  phone text default '', whatsapp text default '', email text default '', instagram text default '', facebook text default '', tiktok text default '', youtube text default '', logo_url text default '', favicon_url text default '', hero_image text default '',
  hero_title text default 'ANSTERDAM', hero_subtitle text default 'NIGHT CLUB · PLANÈTE', hero_slogan text default 'Plus qu’une soirée, une expérience.', hero_description text default '', google_maps_url text default '', latitude numeric, longitude numeric, updated_at timestamptz default now()
);
create table if not exists homepage_sections (id uuid primary key default gen_random_uuid(), section_key text unique not null, title text, description text, visible boolean default true, display_order int default 0, created_at timestamptz default now(), updated_at timestamptz default now());
create table if not exists events (id uuid primary key default gen_random_uuid(), title text not null, slug text unique, description text, event_date date, start_time time, end_time time, image_url text, music_style text, featured boolean default false, published boolean default false, display_order int default 0, created_at timestamptz default now(), updated_at timestamptz default now());
create table if not exists gallery_images (id uuid primary key default gen_random_uuid(), image_url text not null, title text, description text, category text, display_order int default 0, published boolean default false, created_at timestamptz default now());
create table if not exists club_spaces (id uuid primary key default gen_random_uuid(), name text not null, title text, description text, image_url text, display_order int default 0, published boolean default false, created_at timestamptz default now(), updated_at timestamptz default now());
create table if not exists service_rooms (id uuid primary key default gen_random_uuid(), name text not null, title text, description text, image_url text, photos jsonb default '[]', features text, availability text, price text, display_order int default 0, published boolean default false, created_at timestamptz default now(), updated_at timestamptz default now());
create table if not exists managers (id uuid primary key default gen_random_uuid(), name text not null, title text, role text, description text, photo_url text, phone text, instagram text, display_order int default 0, published boolean default false, created_at timestamptz default now());
create table if not exists djs (id uuid primary key default gen_random_uuid(), name text not null, title text, stage_name text, specialty text, description text, photo_url text, instagram text, facebook text, display_order int default 0, published boolean default false, created_at timestamptz default now());
create table if not exists reservations (id uuid primary key default gen_random_uuid(), full_name text not null, phone text not null, email text, reservation_date date not null, number_of_people int not null check(number_of_people > 0), reservation_type text not null, message text, status text not null default 'nouvelle' check(status in ('nouvelle','contactée','confirmée','annulée')), admin_note text, created_at timestamptz default now());
create table if not exists contact_messages (id uuid primary key default gen_random_uuid(), name text not null, phone text, email text, subject text not null, message text not null, read boolean default false, created_at timestamptz default now());
create table if not exists opening_hours (id uuid primary key default gen_random_uuid(), name text, title text, day text unique not null, is_open boolean default false, open_time time, close_time time, description text default 'Horaires à confirmer', display_order int default 0, published boolean default true, created_at timestamptz default now(), updated_at timestamptz default now());

create index if not exists events_public_idx on events(published, featured, display_order); create index if not exists gallery_public_idx on gallery_images(published, display_order); create index if not exists reservations_status_idx on reservations(status, created_at desc); create index if not exists messages_read_idx on contact_messages(read, created_at desc);
do $$ declare t text; begin foreach t in array array['site_settings','homepage_sections','events','gallery_images','club_spaces','service_rooms','managers','djs','reservations','contact_messages','opening_hours'] loop execute format('alter table %I enable row level security', t); end loop; end $$;
do $$ declare t text; begin foreach t in array array['homepage_sections','events','gallery_images','club_spaces','service_rooms','managers','djs','opening_hours'] loop execute format('create policy "public_read_published_%s" on %I for select to anon using (%s)', t, t, case when t='homepage_sections' then 'visible = true' else 'published = true' end); end loop; exception when duplicate_object then null; end $$;
create policy "public_read_settings" on site_settings for select to anon using (true);
create policy "public_create_reservations" on reservations for insert to anon with check (status = 'nouvelle' and admin_note is null);
create policy "public_create_messages" on contact_messages for insert to anon with check (read = false);
do $$ declare t text; begin foreach t in array array['site_settings','homepage_sections','events','gallery_images','club_spaces','service_rooms','managers','djs','reservations','contact_messages','opening_hours'] loop execute format('create policy "admin_all_%s" on %I for all to authenticated using (true) with check (true)', t, t); end loop; exception when duplicate_object then null; end $$;
insert into site_settings (id) values (1) on conflict (id) do nothing;
insert into homepage_sections(section_key, title, display_order) values ('hero','Hero',1),('values','Valeurs',2),('about','À propos',3),('spaces','Espaces',4),('rooms','Chambres',5),('events','Événements',6),('gallery','Galerie',7),('managers','Gérantes',8),('djs','DJ',9),('reservation','Réservation',10),('contact','Contact',11),('location','Localisation',12),('hours','Horaires',13) on conflict(section_key) do nothing;
insert into opening_hours(day,name,title,display_order) values ('Lundi','Lundi','Lundi',1),('Mardi','Mardi','Mardi',2),('Mercredi','Mercredi','Mercredi',3),('Jeudi','Jeudi','Jeudi',4),('Vendredi','Vendredi','Vendredi',5),('Samedi','Samedi','Samedi',6),('Dimanche','Dimanche','Dimanche',7) on conflict(day) do nothing;

insert into storage.buckets (id, name, public, file_size_limit, allowed_mime_types) values ('site-images','site-images',true,5242880,array['image/jpeg','image/png','image/webp','image/avif']) on conflict(id) do update set public=true;
create policy "public_view_site_images" on storage.objects for select to anon using (bucket_id='site-images');
create policy "admin_manage_site_images" on storage.objects for all to authenticated using (bucket_id='site-images') with check (bucket_id='site-images');
