import { ArrowDown, ArrowUp, Eye, EyeOff, Pencil, Plus, Search, Trash2, X } from 'lucide-react'
import { useEffect as reactUseEffect, useMemo, useState, type DependencyList, type FormEvent } from 'react'
import { Button } from '../../components/shared/Button'
import { ImageUploader } from '../../components/admin/ImageUploader'
import { deleteContent, listContent, saveContent } from '../../services/content'
import type { ContentItem } from '../../types'
type Table = 'events' | 'gallery_images' | 'club_spaces' | 'service_rooms' | 'managers' | 'djs' | 'opening_hours'
const useEffect = (effect: () => Promise<unknown>, dependencies: DependencyList) => reactUseEffect(() => { void effect() }, dependencies)
const titles: Record<Table, string> = { events: 'Événements', gallery_images: 'Galerie', club_spaces: 'Espaces du club', service_rooms: 'Chambres de service', managers: 'Gérantes', djs: 'DJ', opening_hours: 'Horaires' }
export function CrudPage({ table }: { table: Table }) { const [rows, setRows] = useState<ContentItem[]>([]); const [editing, setEditing] = useState<ContentItem | null>(null); const [search, setSearch] = useState(''); const [toast, setToast] = useState(''); const load = () => listContent(table, true).then(setRows); useEffect(load, [table]); const filtered = useMemo(() => rows.filter(x => String(x.title || x.name || x.day).toLowerCase().includes(search.toLowerCase())), [rows, search]); async function remove(id: string) { if (!confirm('Supprimer définitivement cet élément ?')) return; await deleteContent(table, id); setToast('Élément supprimé.'); load() } async function toggle(row: ContentItem) { await saveContent(table, { ...row, published: row.published === false }); load() } async function move(row: ContentItem, delta: number) { await saveContent(table, { ...row, display_order: Number(row.display_order || 0) + delta }); load() }
  return <div className="admin-page"><div className="admin-title"><div><span>GESTION DU CONTENU</span><h1>{titles[table]}</h1></div><Button onClick={() => setEditing({ id: crypto.randomUUID(), published: true, display_order: rows.length + 1 })}><Plus /> AJOUTER</Button></div>{toast && <div className="toast">{toast}</div>}<div className="toolbar"><Search /><input placeholder="Rechercher…" value={search} onChange={e => setSearch(e.target.value)} /></div>{filtered.length ? <div className="admin-table"><div className="table-row heading"><span>Contenu</span><span>État</span><span>Ordre</span><span>Actions</span></div>{filtered.sort((a, b) => Number(a.display_order) - Number(b.display_order)).map(row => <div className="table-row" key={row.id}><div><b>{String(row.title || row.name || row.day || 'Sans titre')}</b><small>{String(row.description || row.specialty || row.role || '')}</small></div><span className={`status ${row.published === false ? 'hidden' : ''}`}>{row.published === false ? 'Masqué' : 'Publié'}</span><div className="order"><button onClick={() => move(row, -1)} aria-label="Monter"><ArrowUp /></button><b>{String(row.display_order || 0)}</b><button onClick={() => move(row, 1)} aria-label="Descendre"><ArrowDown /></button></div><div className="actions"><button onClick={() => toggle(row)} aria-label="Changer visibilité">{row.published === false ? <Eye /> : <EyeOff />}</button><button onClick={() => setEditing(row)} aria-label="Modifier"><Pencil /></button><button className="danger-icon" onClick={() => remove(row.id)} aria-label="Supprimer"><Trash2 /></button></div></div>)}</div> : <div className="empty">Aucun contenu. Utilisez « Ajouter » pour commencer.</div>}{editing && <EditModal table={table} row={editing} close={() => setEditing(null)} saved={() => { setEditing(null); setToast('Modifications enregistrées.'); load() }} />}</div> }
function EditModal({ table, row, close, saved }: { table: Table; row: ContentItem; close: () => void; saved: () => void }) { const [image, setImage] = useState(String(row.image_url || row.photo_url || '')); const [busy, setBusy] = useState(false); async function submit(e: FormEvent<HTMLFormElement>) { e.preventDefault(); setBusy(true); const f = new FormData(e.currentTarget); const obj: ContentItem = { ...row, title: String(f.get('title')), name: String(f.get('title')), description: String(f.get('description')), image_url: image, photo_url: image, published: f.get('published') === 'on', display_order: Number(f.get('display_order')) }; ['event_date', 'music_style', 'availability', 'price', 'role', 'stage_name', 'specialty', 'day', 'open_time', 'close_time'].forEach(k => { const v = f.get(k); if (v !== null) obj[k] = String(v) }); await saveContent(table, obj); setBusy(false); saved() } const fields = table === 'events' ? [['event_date', 'Date', 'date'], ['music_style', 'Style musical', 'text']] : table === 'service_rooms' ? [['availability', 'Disponibilité', 'text'], ['price', 'Prix facultatif', 'text']] : table === 'managers' ? [['role', 'Poste', 'text']] : table === 'djs' ? [['stage_name', 'Nom de scène', 'text'], ['specialty', 'Style musical', 'text']] : table === 'opening_hours' ? [['day', 'Jour', 'text'], ['open_time', 'Ouverture', 'time'], ['close_time', 'Fermeture', 'time']] : []; return <div className="modal-backdrop"><form className="edit-modal" onSubmit={submit}><div className="modal-title"><h2>Modifier</h2><button type="button" onClick={close}><X /></button></div><label>Nom / titre<input name="title" defaultValue={String(row.title || row.name || row.day || '')} required /></label><label>Description<textarea name="description" rows={4} defaultValue={String(row.description || '')} /></label>{fields.map(([name, label, type]) => <label key={name}>{label}<input name={name} type={type} defaultValue={String(row[name] || '')} /></label>)}{table !== 'opening_hours' && <ImageUploader value={image} onChange={setImage} folder={table} />}<label>Ordre<input name="display_order" type="number" defaultValue={Number(row.display_order || 0)} /></label><label className="check"><input name="published" type="checkbox" defaultChecked={row.published !== false} /> Visible / publié</label><div className="modal-actions"><Button type="button" variant="secondary" onClick={close}>ANNULER</Button><Button loading={busy}>ENREGISTRER</Button></div></form></div> }
