import { useEffect, useState, type FormEvent } from 'react'
import { Button } from '../../components/shared/Button'
import { ImageUploader } from '../../components/admin/ImageUploader'
import { settings as defaults } from '../../data/defaults'
import { getSettings, saveSettings } from '../../services/content'
import type { SiteSettings } from '../../types'
const fields: [keyof SiteSettings, string, string][] = [['club_name', 'Nom du club', 'text'], ['location_name', 'Mention / lieu', 'text'], ['address', 'Adresse', 'text'], ['phone', 'Téléphone', 'tel'], ['whatsapp', 'WhatsApp', 'tel'], ['email', 'Email', 'email'], ['instagram', 'Instagram', 'url'], ['facebook', 'Facebook', 'url'], ['tiktok', 'TikTok', 'url'], ['youtube', 'YouTube', 'url'], ['google_maps_url', 'Lien Google Maps', 'url'], ['latitude', 'Latitude', 'text'], ['longitude', 'Longitude', 'text']]
export function SettingsPage() { const [value, setValue] = useState(defaults); const [busy, setBusy] = useState(false); const [toast, setToast] = useState(''); useEffect(() => { getSettings().then(setValue) }, []); async function submit(e: FormEvent) { e.preventDefault(); setBusy(true); await saveSettings(value); setBusy(false); setToast('Paramètres enregistrés.') } return <div className="admin-page"><div className="admin-title"><div><span>CONFIGURATION</span><h1>Paramètres généraux</h1></div></div>{toast && <div className="toast">{toast}</div>}<form className="settings-form" onSubmit={submit}><div className="form-grid">{fields.map(([name, label, type]) => <label key={name}>{label}<input type={type} value={value[name]} onChange={e => setValue({ ...value, [name]: e.target.value })} /></label>)}</div><h2>Logo et favicon</h2><ImageUploader value={value.logo_url} onChange={logo_url => setValue({ ...value, logo_url })} folder="branding" /><Button loading={busy}>ENREGISTRER LES PARAMÈTRES</Button></form></div> }
export function HomepagePage() { const [value, setValue] = useState(defaults); const [busy, setBusy] = useState(false); const [toast, setToast] = useState(''); useEffect(() => { getSettings().then(setValue) }, []); async function submit(e: FormEvent) { e.preventDefault(); setBusy(true); await saveSettings(value); setBusy(false); setToast('Page d’accueil enregistrée.') } return <div className="admin-page"><div className="admin-title"><div><span>CONTENU PUBLIC</span><h1>Page d’accueil</h1></div><a className="btn btn-outline" href="/" target="_blank">PRÉVISUALISER</a></div>{toast && <div className="toast">{toast}</div>}<form className="settings-form" onSubmit={submit}><h2>Hero</h2><ImageUploader value={value.hero_image} onChange={hero_image => setValue({ ...value, hero_image })} folder="hero" /><div className="form-grid"><label>Titre<input value={value.hero_title} onChange={e => setValue({ ...value, hero_title: e.target.value })} /></label><label>Sous-titre<input value={value.hero_subtitle} onChange={e => setValue({ ...value, hero_subtitle: e.target.value })} /></label><label className="full">Slogan<input value={value.hero_slogan} onChange={e => setValue({ ...value, hero_slogan: e.target.value })} /></label><label className="full">Description<textarea rows={5} value={value.hero_description} onChange={e => setValue({ ...value, hero_description: e.target.value })} /></label></div><h2>Sections</h2><p>Les espaces, chambres, événements, galerie, gérantes, DJ et horaires se gèrent depuis leurs menus respectifs. Leur ordre est modifiable avec les flèches.</p><Button loading={busy}>ENREGISTRER</Button></form></div> }
